index:  
    path: /welcome
    controller: App\Controller\StudentController::index

teacher:
    path: /teacher/{name}
    controller: App\Controller\TeacherController::showTeacher

go_to_index:
    path: /gotoindex
    controller: App\Controller\TeacherController::goToIndex
